# For loki
[[override]]
  name = "github.com/cortexproject/cortex"
  source = "github.com/grafana/cortex"
  branch = "dev"

[[override]]
  name = "github.com/weaveworks/common"
  source = "github.com/tomwilkie/weaveworks-common"
  branch = "dev"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

# For Prometheus

[[override]]
  name = "k8s.io/api"
  revision = "072894a440bdee3a891dea811fe42902311cd2a3"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "103fd098999dc9c0c88536f5c9ad2e5da39373ae"

[[override]]
  name = "k8s.io/client-go"
  version = "v8.0.0"

[[override]]
  name = "github.com/ugorji/go"
  revision = "708a42d246822952f38190a8d8c4e6b16a0e600c"

[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  revision = "bd73d950fa4440dae889bd9917bff7cef539f86e"

[[override]]
  name = "github.com/Azure/go-autorest"
  version = "10.8.1"

[[override]]
  name = "github.com/prometheus/prometheus"
  revision = "cd491e2d3a4dd225ea352a0a98cc3343c204528e"

[[override]]
  name = "github.com/miekg/dns"
  revision = "eac804ceef194db2da6ee80c728d7658c8c805ff"

[prune]
  go-tests = true
  unused-packages = true
